### ISSUE TITLE
Wx_tools/monitor_new_wx bug: 'overlay' is not valid for if_sheet_exists. Valid options are 'error', 'new' and 'replace'

### ISSUE THREAD

**Issue by perkupup** [eeeeeeeeee-code/e0e1-wx#12]
Wx_tools/monitor_new_wx bug: 'overlay' is not valid for if_sheet_exists. Valid options are 'error', 'new' and 'replace'
![image](https://github.com/eeeeeeeeee-code/e0e1-wx/assets/98009359/0d70f801-3085-40ff-90a9-cc12c70373a2)

**Comment by eeeeeeeeee-code** [comment]
估计是pandas版本不同

**Comment by eeeeeeeeee-code** [comment]
你将这两个删除看看，有没有问题，300多行这里
![image](https://github.com/eeeeeeeeee-code/e0e1-wx/assets/115862499/35e1e266-2a88-4e34-9ca0-8e1f90b501e8)

**Comment by eeeeeeeeee-code** [comment]
已优化

**Comment by eeeeeeeeee-code** [comment]
有问题，请重新下载

**Comment by lueluelueya** [comment]
新版本永久，pandas版本是1.3.5

**Comment by lueluelueya** [comment]
新版本依旧，panda版本是1.3.5，2.0.1版本要更新python

**Comment by eeeeeeeeee-code** [comment]
> 新版本依旧，panda版本是1.3.5，2.0.1版本要更新python

openpyxl pip安转一下看看

**Comment by lueluelueya** [comment]
> > 新版本依旧，panda版本是1.3.5，2.0.1版本要更新python
> 
> openpyxl pip安转一下看看
openpyxl           3.1.3，永久

**Comment by lueluelueya** [comment]
> > 新版本依旧，panda版本是1.3.5，2.0.1版本要更新python
> 
> openpyxl pip安转一下看看

openpyxl           3.1.3，依旧

**Comment by eeeeeeeeee-code** [comment]
你是python3.几

**Comment by eeeeeeeeee-code** [comment]
> > > 新版本依旧，panda版本是1.3.5，2.0.1版本要更新python
> > 
> > 
> > openpyxl pip安转一下看看
> 
> openpyxl 3.1.3，依旧

你是python3.几

**Comment by lueluelueya** [comment]
> > > > 新版本依旧，panda版本是1.3.5，2.0.1版本要更新python
> > > 
> > > 
> > > openpyxl pip安转一下看看
> > 
> > 
> > openpyxl 3.1.3，依旧
> 
> 你是python3.几

Python 3.7.4

**Comment by eeeeeeeeee-code** [comment]
> > > > > 新版本依旧，panda版本是1.3.5，2.0.1版本要更新python
> > > > 
> > > > 
> > > > openpyxl pip安转一下看看
> > > 
> > > 
> > > openpyxl 3.1.3，依旧
> > 
> > 
> > 你是python3.几
> 
> Python 3.7.4

panda 我本地的是2.0.1，你可以单独下载一个python高版本，用他的python.exe pip安装完，直接用它python.exe试试？

**Comment by lueluelueya** [comment]
> > > > > > 新版本依旧，panda版本是1.3.5，2.0.1版本要更新python
> > > > > 
> > > > > 
> > > > > openpyxl pip安转一下看看
> > > > 
> > > > 
> > > > openpyxl 3.1.3，依旧
> > > 
> > > 
> > > 你是python3.几
> > 
> > 
> > Python 3.7.4
> 
> panda 我本地的是2.0.1，你可以单独下载一个python高版本，用他的python.exe pip安装完，直接用它python.exe试试？

更新到python 3.8.7使用是正常的，把新版本 pandas或者python.exe替换python 3.7.4的文件都不行

**Comment by clingerxiangdingdang** [comment]
Python 3.11.5为什么不行？@eeeeeeeeee-code

**Comment by eeeeeeeeee-code** [comment]
报错是什么也不发一下，我要知道具体是什么问题诶

> Python 3.11.5为什么不行？@eeeeeeeeee-code

**Comment by wind-cyber** [comment]
> 你将这两个删除看看，有没有问题，300多行这里 ![image](https://private-user-images.githubusercontent.com/115862499/334377633-35e1e266-2a88-4e34-9ca0-8e1f90b501e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNDI1ODcsIm5iZiI6MTcxNzM0MjI4NywicGF0aCI6Ii8xMTU4NjI0OTkvMzM0Mzc3NjMzLTM1ZTFlMjY2LTJhODgtNGUzNC05Y2EwLThlMWY5MGI1MDFlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxNTMxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzYwNTA1YzQwNDNjYWU0MTY5Y2Y2NDJlNTQxOTk2ZTk4Njc0Y2FlNzE4NDIxMWEwOTJkNjNjOWYwZThjNjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T3Bw0nmZDymLe43kvQtmCMsMNb9JtcLVdcLCTyCYZ3A)

Python 版本3.7.9删除掉可以正常使用了。

**Comment by eeeeeeeeee-code** [comment]
> > 报错是什么也不发一下，我要知道具体是什么问题诶
> > > Python 3.11.5为什么不行？@eeeeeeeeee-code
> 
> 留个联系方式，反正就是不行

不是呀，我是搞开源的，传承分享的理念，又不是闭源搞钱，报错还是要给其他同样问题的人一个参考，什么报错不发我怎么知道你遇到的问题，实在不行，你换到3.8版本吧啊

**Comment by eeeeeeeeee-code** [comment]
> > > > > > > 新版本依旧，panda版本是1.3.5，2.0.1版本要更新python
> > > > > > 
> > > > > > 
> > > > > > openpyxl pip安转一下看看
> > > > > 
> > > > > 
> > > > > openpyxl 3.1.3，依旧
> > > > 
> > > > 
> > > > 你是python3.几
> > > 
> > > 
> > > Python 3.7.4
> > 
> > 
> > panda 我本地的是2.0.1，你可以单独下载一个python高版本，用他的python.exe pip安装完，直接用它python.exe试试？
> 
> 更新到python 3.8.7使用是正常的，把新版本 pandas或者python.exe替换python 3.7.4的文件都不行

okok，能正常使用就ok了，我那时候是根据自己的环境写的，不太容易注意别的环境

**Comment by Tears-of-the-sun** [comment]
我这里改成了new,一样可以用
