### ISSUE TITLE
hook--F12不行，微信版本太高

### ISSUE THREAD

**Issue by banhongwei1314** [eeeeeeeeee-code/e0e1-wx#14]
在%appdata%\Tencent\WeChat\XPlugin\Plugins\RadiumWMPF\文件夹中，最新版本是9165，已经测试旧版本的9129，进不去F12。是不是需要大佬更新一下最新版本的addres参数
![Uploading image.png…]()

**Comment by eeeeeeeeee-code** [comment]
新版的就算hook了，也不好用，建议看看这个，如何切换老版本的devtools，https://github.com/eeeeeeeeee-code/wx-hook

**Comment by banhongwei1314** [comment]
嗯嗯好的
