### ISSUE TITLE
Wx_tools/monitor_new_wx bug: Length mismatch: Expected axis has 0 elements, new values have 3 elements

### ISSUE THREAD

**Issue by ZT124** [eeeeeeeeee-code/e0e1-wx#16]
将微信文件替换为8447后，出现bug
Wx_tools/monitor_new_wx bug: Length mismatch: Expected axis has 0 elements, new values have 3 elements
![image](https://github.com/eeeeeeeeee-code/e0e1-wx/assets/62941359/5a7840f7-1c0e-409b-81b3-ddff35411b39)

**Comment by eeeeeeeeee-code** [comment]
读取的内容有一个整个列表空，然而标准输入应该三个内容段，我看看那里没加try

**Comment by eeeeeeeeee-code** [comment]
已更新，请重新下载，更换看看

**Comment by ZT124** [comment]
您好，问题已经解决，感谢分享！
