### ISSUE TITLE
devtools无法替代本地文件

### ISSUE THREAD

**Issue by Rabb1ter** [eeeeeeeeee-code/e0e1-wx#20]
这边没有替换的选项
<img width="582" alt="image" src="https://github.com/user-attachments/assets/7d67cee4-8543-4072-a786-2e5cee954be6">

这边的选择本地文件无法点击
<img width="357" alt="image" src="https://github.com/user-attachments/assets/489eb9ae-c11e-4193-a120-6336fb11c747">

**Comment by Rabb1ter** [comment]
我用的是8461，我不知道是不是版本问题，如果有高版本可以替换功能的话麻烦推荐一下

**Comment by eeeeeeeeee-code** [comment]
这个我没搞过

**Comment by eeeeeeeeee-code** [comment]
我主要是云函数之类的
