### ISSUE TITLE
没有wxml文件

### ISSUE THREAD

**Issue by yqchilde** [eeeeeeeeee-code/e0e1-wx#21]
大佬感谢开源项目
我执行成功后的小程序包里都缺失了对应的页面wxml，这个是什么问题导致呢，不过可以通过vconsole里看到手动复制下

用的8555

**Comment by eeeeeeeeee-code** [comment]
可能是工具的原因吧，我懒的去搞那个解析小程序反编译文件的部分，找了一个工具搞的，回头我看看吧，最近挺忙，有时间优化优化，最近还在写一些别的东西

**Comment by yqchilde** [comment]
👌

**Comment by eeeeeeeeee-code** [comment]
更新了

**Comment by eeeeeeeeee-code** [comment]
github库覆盖不上去，直接从releases下载吧

**Comment by yqchilde** [comment]
> github库覆盖不上去，直接从releases下载吧

好的，晚上回去我试试，🙏
