### ISSUE TITLE
一直反编译失败，换热点也不行

### ISSUE THREAD

**Issue by Dioni404** [eeeeeeeeee-code/e0e1-wx#22]
一直失败，重启电脑也不行，换网络也不行
![image](https://github.com/user-attachments/assets/5aef0a10-08e9-4893-9a81-ae3f4127d1de)

**Comment by eeeeeeeeee-code** [comment]
有一些玄学问题，我有时候也有点懵，最近比赛太多了，我比赛完了，回来排查排查

**Comment by Superhero-zero** [comment]
+1 一直反编译错误 如图所示

**Comment by eeeeeeeeee-code** [comment]
去releases下载新版本看看

**Comment by Superhero-zero** [comment]
就是从releases下载的

**Comment by eeeeeeeeee-code** [comment]
那我有时间再看看，最近比赛特别多，没时间搞

**Comment by sumo166** [comment]
![Clip_2024-11-28_10-27-55](https://github.com/user-attachments/assets/735f0fbe-b566-4175-a7e2-eac5144d76d3)
 一样一样有bug

**Comment by eeeeeeeeee-code** [comment]
> ![Clip_2024-11-28_10-27-55](https://private-user-images.githubusercontent.com/47419184/390618452-735f0fbe-b566-4175-a7e2-eac5144d76d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODU5NjksIm5iZiI6MTczMjc4NTY2OSwicGF0aCI6Ii80NzQxOTE4NC8zOTA2MTg0NTItNzM1ZjBmYmUtYjU2Ni00MTc1LWE3ZTItZWFjNTE0NGQ3NmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA5MjEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMmQ0MGJkNzcwY2Y1YjM2ODVlM2Y1YzA1Y2VjMzY4NTBjZTZiYWQ4NDcxOTUxMzIzNjkwMjI2MWUxYjRjMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J0LkpfGgr11Fif_uxYbQVgkhnt45FoiZcWBdiMwoRvo) 一样一样有bug

我今天看看能不能找到问题，因为我自己这里从来没遇到过这个问题，最近在写一个javafx项目，忘记去搞这个了

**Comment by eeeeeeeeee-code** [comment]
下载新版看看
