### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by erdan111** [eeeeeeeeee-code/e0e1-wx#25]
![image](https://github.com/user-attachments/assets/1f7ef54e-6963-4fe3-b648-834777d2c060)
pywin32-305不满足我换成了pywin32-306
![image](https://github.com/user-attachments/assets/1a10b26c-3627-4730-8d8b-303660c81df4)
为什么执行不起来

**Comment by eeeeeeeeee-code** [comment]
这感觉像是你自己命令行的问题诶

**Comment by eeeeeeeeee-code** [comment]
你有python3的环境变量吗

**Comment by erdan111** [comment]
解决了，谢谢
