### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Emper0rc4** [eeeeeeeeee-code/e0e1-wx#3]
Traceback (most recent call last):
  File "e0e1-wx.py", line 587, in <module>
    wx_tools = Wx_tools()
  File "e0e1-wx.py", line 334, in __init__
    self.root_path = CONFIG().wx_file + "/Applet"
  File "e0e1-wx.py", line 36, in __init__
    config = safe_load(open(config_path, "r", encoding="gb18030").read())
UnicodeDecodeError: 'gb18030' codec can't decode byte 0x80 in position 19: illegal multibyte sequence

**Comment by eeeeeeeeee-code** [comment]
编码问题，yaml文件中有中文的缘故把，有的不会出问题，有的会出问题，我试试解决如何适应所有环境，感谢反馈

**Comment by eeeeeeeeee-code** [comment]
添加了utf-8编码，去除config.yaml中的中文，请重新下载，再看看有没有问题

**Comment by Emper0rc4** [comment]
> 添加了utf-8编码，去除config.yaml中的中文，请重新下载，再看看有没有问题

已经解决，没问题了

**Comment by eeeeeeeeee-code** [comment]
还有注意，yaml中wx文件夹参数，必须使用的是单引号
