### ISSUE TITLE
可以动态调试小程序的js么？

### ISSUE THREAD

**Issue by niuxuefeng87** [eeeeeeeeee-code/e0e1-wx#6]
你好 按照req安装好库，并成功使用，但是想像浏览器F12那样动态调试，这个工程的方法支持么

**Comment by eeeeeeeeee-code** [comment]
这可能需要之前的devtools，这个9开头的版本的devtools可能不太好用，回头我试试看看能不能搞成原来8版本的devtools，不过不确定能不能调试

**Comment by eeeeeeeeee-code** [comment]
我需要去找找老版本的版本，回头这两天，更新更新如何切换到老版本的devtools，就是这种状态
![image](https://github.com/eeeeeeeeee-code/e0e1-wx/assets/115862499/28d3bc3c-a672-47aa-a91d-36c8854bad88)

**Comment by eeeeeeeeee-code** [comment]
文件更新，自行查看 https://github.com/eeeeeeeeee-code/wx-hook 如何hook以前的devtools

**Comment by niuxuefeng87** [comment]
3q
