### ISSUE TITLE
中文路径乱码导致报错

### ISSUE THREAD

**Issue by nonu11** [eeeeeeeeee-code/e0e1-wx#7]
![图片](https://github.com/eeeeeeeeee-code/e0e1-wx/assets/17950878/52ea90a3-07dc-48ab-922e-e7afba36b1c5)

**Comment by eeeeeeeeee-code** [comment]
微信位置可以更改的，改成英文的吧，中文这种确实没有考

**Comment by nonu11** [comment]
我尝试调整默认打开配置文件编码格式为utf-8后可以正常读取，建议调整utf-8编码优先级，目前多数文件默认编码格式为utf-8。
![图片](https://github.com/eeeeeeeeee-code/e0e1-wx/assets/17950878/f9639956-9085-4bca-865d-06ce3328bcb3)

**Comment by eeeeeeeeee-code** [comment]
这个就是读取配置文件呀，优先就是utf-8编码呀，出现错误，就采用gb18030编码

**Comment by eeeeeeeeee-code** [comment]
确实也行

**Comment by nonu11** [comment]
上面图片中是我改完的，原来优先是gb18030，出错才使用utf-8

**Comment by eeeeeeeeee-code** [comment]
gb18030范围太广，通常不会出错，他出错了，utf-8也跑不了，原来的try前面已经更改了，感谢反馈

**Comment by eeeeeeeeee-code** [comment]
两个编码位置已经切换
