### ISSUE TITLE
Wx_tools/monitor_new_wx bug: [WinError 3] 系统找不到指定的路径。: './result/***'

### ISSUE THREAD

**Issue by czy521** [eeeeeeeeee-code/e0e1-wx#8]
![微信截图_20240515180900](https://github.com/eeeeeeeeee-code/e0e1-wx/assets/54525249/8921307a-cd21-44c5-aa3e-0da7a44f81be)

不知道啥原因

**Comment by eeeeeeeeee-code** [comment]
你有没有result文件夹呀

**Comment by czy521** [comment]
> 你有没有result文件夹呀

![微信截图_20240515200543](https://github.com/eeeeeeeeee-code/e0e1-wx/assets/54525249/81c4ea5f-454b-43cf-b70e-abb0bf3a2c6c)
有的，是这个吧

**Comment by eeeeeeeeee-code** [comment]
后面都有这个问题吗？

**Comment by eeeeeeeeee-code** [comment]
先重启微信试一下

**Comment by eeeeeeeeee-code** [comment]
如果还是这个问题的话，我回头尝试尝试复现看看什么问题

**Comment by czy521** [comment]
> 如果还是这个问题的话，我回头尝试尝试复现看看什么问题

嗯嗯，还是这个问题

**Comment by eeeeeeeeee-code** [comment]
你邮箱有吗，微信私聊，我看看什么问题
