### ISSUE TITLE
反编译后把反编译的文件删了后就不反编译了是咋个回事

### ISSUE THREAD

**Issue by crab890715** [eeeeeeeeee-code/e0e1-wx#9]

**Comment by eeeeeeeeee-code** [comment]
因为他的加密文件被记录了，他被反编译过了，为了不重复执行，浪费时间呀，但是你关闭脚本，重新开，他就还是可以反编译的呀

**Comment by eeeeeeeeee-code** [comment]
毕竟反编译完成了，自己把反编译文件删除，肯定不在考虑范围内呀，而且只要重启脚本，记录消失还是可以反编译的呀

**Comment by crab890715** [comment]
重启脚本后还是不生成

**Comment by crab890715** [comment]
你的记录是记录在内存还是文件的，我感觉被记录在文件什么地方了

**Comment by eeeeeeeeee-code** [comment]
记录是跟脚本一块儿的，用参数记录的，重启肯定会消失的，你小程序有没有重启，让脚本检测到，光重启脚本，检测不到加密文件的，脚本先重启，然后再关闭小程序，再打开，看看

**Comment by crab890715** [comment]
嗯，可以了，可能有些什么残余进程什么的影响了

**Comment by eeeeeeeeee-code** [comment]
okok
